// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs2wGk47kZo0wl9jY_qDQ6B4dARgpl85c',
    appId: '1:824323218293:web:REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: '824323218293',
    projectId: 'fitmotionai-8220a',
    storageBucket: 'fitmotionai-8220a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs2wGk47kZo0wl9jY_qDQ6B4dARgpl85c',
    appId: '1:824323218293:android:29e0255830faad28e5913c',
    messagingSenderId: '824323218293',
    projectId: 'fitmotionai-8220a',
    storageBucket: 'fitmotionai-8220a.firebasestorage.app',
  );
}
